services:
  - type: web
    name: inventory-backend
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate --noinput
      python manage.py collectstatic --noinput
    startCommand: gunicorn inventory_project.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        fromDatabase:
          name: inventory-db
          property: password
  - type: pserv
    name: inventory-db
    env: postgres
    plan: free
    ipAllowList: []
    maxConnections: 20
